# vim:ft=kitty
## name: Duskfox
## author: EdenEast (nightfox.nvim)
## license: MIT
## blurb: Dark, purple-leaning variant of the Nightfox colorscheme family

foreground            #e0def4
background            #232136
selection_foreground  #e0def4
selection_background  #433c59
cursor                #e0def4
cursor_text_color     #232136

color0  #393552
color8  #47407d
color1  #eb6f92
color9  #f083a2
color2  #a3be8c
color10 #b1d196
color3  #f6c177
color11 #f9cb8c
color4  #569fba
color12 #65b1cd
color5  #c4a7e7
color13 #ccb1ed
color6  #9ccfd8
color14 #a6dae3
color7  #e0def4
color15 #e2e0f7
