# vim:ft=kitty
## name: Terafox
## author: EdenEast (nightfox.nvim)
## license: MIT
## blurb: Dark, teal/green variant of the Nightfox colorscheme family

foreground            #e6eaea
background            #152528
selection_foreground  #e6eaea
selection_background  #293e40
cursor                #e6eaea
cursor_text_color     #152528

color0  #2f3239
color8  #4e5157
color1  #e85c51
color9  #eb746b
color2  #7aa4a1
color10 #8eb2af
color3  #fda47f
color11 #fdb292
color4  #5a93aa
color12 #73a3b7
color5  #ad5c7c
color13 #b97490
color6  #a1cdd8
color14 #afd4de
color7  #ebebeb
color15 #eeeeee
