# vim:ft=kitty
## name: VSCode_Light
## author: derived from Mofiqul/vscode.nvim's own Light+ palette source
## license: MIT
## blurb: the integrated terminal's default light theme

foreground            #343434
background            #ffffff
selection_foreground  #343434
selection_background  #add6ff
cursor                #000000
cursor_text_color     #ffffff

color0  #000000
color8  #767676
color1  #ff0000
color9  #a31515
color2  #008000
color10 #587c0c
color3  #795e26
color11 #895503
color4  #007acc
color12 #0064c1
color5  #af00db
color13 #af00db
color6  #267f99
color14 #267f99
color7  #d2d2d2
color15 #929292
